"""Initial schema

Revision ID: 1cc95008a447
Revises:
Create Date: 2026-09-23 20:08:07.687703+00:00

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1cc95008a447"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "QUEUED", "RUNNING", "COMPLETED", "PARTIAL", "FAILED", name="analysis_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("stages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overview", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("total_duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_runs")),
    )
    op.create_index(
        op.f("ix_analysis_runs_document_id"), "analysis_runs", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_analysis_runs_status"), "analysis_runs", ["status"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("USER", "ASSISTANT", "SYSTEM", name="message_role_enum"),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "answer_status",
            postgresql.ENUM(
                "SUPPORTED",
                "PARTIALLY_SUPPORTED",
                "UNSUPPORTED",
                "UNVERIFIED",
                name="answer_status_enum",
            ),
            nullable=True,
        ),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(
        op.f("ix_chat_messages_session_id"), "chat_messages", ["session_id"], unique=False
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_sessions")),
    )
    op.create_index(
        op.f("ix_chat_sessions_document_id"), "chat_sessions", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_chat_sessions_owner_id"), "chat_sessions", ["owner_id"], unique=False)
    op.create_table(
        "checklist_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "NOT_APPLICABLE",
                name="checklist_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_items")),
    )
    op.create_index(
        op.f("ix_checklist_items_analysis_id"), "checklist_items", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_checklist_items_document_id"), "checklist_items", ["document_id"], unique=False
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=True),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column("claim", sa.String(), nullable=False),
        sa.Column("supporting_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "support_status",
            postgresql.ENUM(
                "SUPPORTED",
                "PARTIALLY_SUPPORTED",
                "UNSUPPORTED",
                "UNVERIFIED",
                name="support_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("verification_notes", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
    )
    op.create_index(op.f("ix_claims_analysis_id"), "claims", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_claims_message_id"), "claims", ["message_id"], unique=False)
    op.create_table(
        "clauses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("heading", sa.String(), nullable=True),
        sa.Column("original_text", sa.String(), nullable=False),
        sa.Column("normalized_text", sa.String(), nullable=False),
        sa.Column("page_start", sa.BigInteger(), nullable=False),
        sa.Column("page_end", sa.BigInteger(), nullable=False),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("char_start", sa.BigInteger(), nullable=True),
        sa.Column("char_end", sa.BigInteger(), nullable=True),
        sa.Column("source_block_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "clause_type",
            postgresql.ENUM(
                "PAYMENT_FEES",
                "TERM_RENEWAL",
                "TERMINATION_NOTICE",
                "LIABILITY_INDEMNITY",
                "CONFIDENTIALITY_IP",
                "NON_COMPETE_NON_SOLICIT",
                "DISPUTE_GOVERNING_LAW",
                "PRIVACY_DATA",
                "BOILERPLATE",
                "MISCELLANEOUS",
                "OTHER",
                name="clause_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clauses")),
    )
    op.create_index(op.f("ix_clauses_document_id"), "clauses", ["document_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "UPLOADING",
                "QUEUED",
                "VALIDATING",
                "EXTRACTING",
                "ANALYZING",
                "INDEXING",
                "GENERATING",
                "VERIFYING",
                "COMPLETED",
                "PARTIAL",
                "FAILED",
                "DELETED",
                name="document_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "document_type",
            postgresql.ENUM(
                "LEGAL_NOTICE",
                "LEASE_AGREEMENT",
                "EMPLOYMENT_AGREEMENT",
                "SERVICE_AGREEMENT",
                "NON_DISCLOSURE_AGREEMENT",
                "PURCHASE_AGREEMENT",
                "POWER_OF_ATTORNEY",
                "COURT_ORDER",
                "INVOICE",
                "OTHER",
                name="document_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("page_count", sa.BigInteger(), nullable=True),
        sa.Column("storage_path", sa.String(), nullable=True),
        sa.Column("analysis_id", sa.String(), nullable=True),
        sa.Column("deleted_at", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_owner_id"), "documents", ["owner_id"], unique=False)
    op.create_index(op.f("ix_documents_sha256"), "documents", ["sha256"], unique=False)
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_table(
        "entities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("clause_id", sa.String(), nullable=True),
        sa.Column(
            "entity_type",
            postgresql.ENUM(
                "DATE",
                "MONEY",
                "PERCENTAGE",
                "DURATION",
                "NOTICE_PERIOD",
                "CLAUSE_NUMBER",
                "STATUTE_REFERENCE",
                "PERSON",
                "ORGANIZATION",
                "ADDRESS",
                name="entity_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("surface_form", sa.String(), nullable=False),
        sa.Column("normalized_value", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("page_number", sa.BigInteger(), nullable=False),
        sa.Column("char_start", sa.BigInteger(), nullable=True),
        sa.Column("char_end", sa.BigInteger(), nullable=True),
        sa.Column(
            "extraction_method",
            postgresql.ENUM("REGEX", "NER", "RULE", "LLM", name="extraction_method_enum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
    )
    op.create_index(op.f("ix_entities_document_id"), "entities", ["document_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("page_number", sa.BigInteger(), nullable=False),
        sa.Column("section_id", sa.String(), nullable=True),
        sa.Column("clause_id", sa.String(), nullable=True),
        sa.Column("quote", sa.String(), nullable=False),
        sa.Column("quote_hash", sa.String(), nullable=False),
        sa.Column("char_start", sa.BigInteger(), nullable=True),
        sa.Column("char_end", sa.BigInteger(), nullable=True),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "source_type",
            postgresql.ENUM(
                "USER_DOCUMENT", "AI_GENERATED", "EXTERNAL_SOURCE", name="source_type_enum"
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            postgresql.ENUM(
                "VERIFIED",
                "OCR_APPROXIMATE",
                "REJECTED",
                "PENDING",
                name="verification_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(op.f("ix_evidence_document_id"), "evidence", ["document_id"], unique=False)
    op.create_index(op.f("ix_evidence_quote_hash"), "evidence", ["quote_hash"], unique=False)
    op.create_table(
        "findings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "FINANCIAL",
                "COMMITMENT",
                "LIABILITY",
                "TERMINATION",
                "CONSISTENCY",
                "MISSING_INFORMATION",
                "DEADLINE",
                "OTHER",
                name="finding_category_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            postgresql.ENUM(
                "IMPORTANT",
                "NEEDS_REVIEW",
                "ATTENTION_REQUIRED",
                "INFORMATION_MISSING",
                name="severity_enum",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("explanation", sa.String(), nullable=False),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("detector_version", sa.String(), nullable=False),
        sa.Column("why_shown", sa.String(), nullable=True),
        sa.Column("cannot_determine", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index(op.f("ix_findings_analysis_id"), "findings", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_findings_document_id"), "findings", ["document_id"], unique=False)
    op.create_table(
        "pages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("page_number", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "text_source",
            postgresql.ENUM("NATIVE_TEXT", "OCR", "MIXED", name="text_source_enum"),
            nullable=False,
        ),
        sa.Column("ocr_quality", sa.Float(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
    )
    op.create_index(op.f("ix_pages_document_id"), "pages", ["document_id"], unique=False)
    op.create_index(op.f("ix_pages_page_number"), "pages", ["page_number"], unique=False)
    op.create_table(
        "sections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("parent_section_id", sa.String(), nullable=True),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("heading", sa.String(), nullable=True),
        sa.Column("page_start", sa.BigInteger(), nullable=False),
        sa.Column("page_end", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
    )
    op.create_index(op.f("ix_sections_document_id"), "sections", ["document_id"], unique=False)
    op.create_table(
        "timeline_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "START_DATE",
                "END_DATE",
                "DEADLINE",
                "NOTICE_PERIOD",
                "PAYMENT_DUE",
                "RENEWAL_WINDOW",
                "TERMINATION_WINDOW",
                "RESPONSE_DEADLINE",
                "OTHER",
                name="timeline_event_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("date_value", sa.String(), nullable=True),
        sa.Column("duration_days", sa.BigInteger(), nullable=True),
        sa.Column(
            "date_status",
            postgresql.ENUM(
                "EXPLICIT", "EXTRACTED", "DERIVED", "INFERRED", name="date_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("calculation_trace", sa.String(), nullable=True),
        sa.Column("evidence_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
    )
    op.create_index(
        op.f("ix_timeline_events_analysis_id"), "timeline_events", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_timeline_events_document_id"), "timeline_events", ["document_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timeline_events_document_id"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_analysis_id"), table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_index(op.f("ix_sections_document_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_pages_page_number"), table_name="pages")
    op.drop_index(op.f("ix_pages_document_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_findings_document_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_analysis_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_evidence_quote_hash"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_document_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_entities_document_id"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_sha256"), table_name="documents")
    op.drop_index(op.f("ix_documents_owner_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_clauses_document_id"), table_name="clauses")
    op.drop_table("clauses")
    op.drop_index(op.f("ix_claims_message_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_analysis_id"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_checklist_items_document_id"), table_name="checklist_items")
    op.drop_index(op.f("ix_checklist_items_analysis_id"), table_name="checklist_items")
    op.drop_table("checklist_items")
    op.drop_index(op.f("ix_chat_sessions_owner_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_document_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_analysis_runs_status"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_document_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    # ### end Alembic commands ###
